print('Привет! Напиши два числа')

j = (input('Первое число: '))
z= (input('Второе число: '))

a = int(j) + int(z)
b = int(j) - int(z)
c = int(z) - int(j)
d = int(j) * int(z)
e = int(j) // int(z)
f = int(z) / int(j)
g = int(j) ** int(z)
h = int(z) ** int(j)

print("Сложение\nответ: ")
print(a)
print('Вычитание\nответ: ')
print(b)
print('Вычитание из второго числа\nответ: ')
print(c)
print('Умножение\nответ: ')
print(d)
print('Деление\nответ: ')
print(e)
print('Деление второго числа\nответ:')
print(f)
print('Возведение в степень первое число вторым\nответ: ')
print(g)
print('Возведение в степень второе число первым\nответ: ')
print(h)
